### ISSUE TITLE
MCU Reset line is permanently low

### ISSUE THREAD

**Issue by alevy** [helena-project/imix#3]
## Cause

Reset line on the FTDI side is shorted to ground in an internal layer. :(
## Workaround

Cut the trace as shown below so that the FTDI side is disconnected from the MCU side. This will allow the MCU to be programmed using a JLink.

![cut_reset](https://cloud.githubusercontent.com/assets/3455487/17618707/162c9130-6036-11e6-9d07-dd2f8cf55f91.png)

**Comment by shaneleonard** [comment]
@alevy It turns out this issue was not due to the diode, but actually due to RESET being shorted to ground near the FTDI chip. The internal ground plane near the FTDI does not have the proper isolation, so it appears to have shorted to the RESET vias. Fortunately, however, this means that the board can actually be completely programmed and powered without adding or removing any components. All that is needed is to cut the trace as shown above.
